### PR TITLE
Put Comments for Search Database Gateway.

### PR DESCRIPTION
**Pull request by MarkianV**

### CODE REVIEW

**Review by danielqiuu — APPROVED** [review]

**Comment by liu-samuel** [comment]
ill approve but idt we need a search gateway. Our listing gateway has this already

**Review by liu-samuel — APPROVED** [review]

**Review by helenastra — DISMISSED** [review]
Follow up with Sam tomorrow, but it may be a good idea to remove it if we don't need it.

**Review by lukecheseldine — APPROVED** [review]
good job!

**Review by liu-samuel — APPROVED** [review]
lgtm

**Review by danielqiuu — APPROVED** [review]

**Pull request merged**
