### PR TITLE
Adding Test and Refactoring

### PR DESCRIPTION
**Pull request by ethanrstark**
so actionPerformed would be cleaner and changed RatingPanel to RatingButton class.

### CODE REVIEW

**Review by lukecheseldine — DISMISSED** [review]

**Review by danielqiuu — DISMISSED** [review]

**Review by helenastra — DISMISSED** [review]
looks good

**Comment by ethanrstark** [comment]
Sorry about the large amount of changed files, most of it was just adding Javadoc. Most of the major changes are in the GUI files in the UI package.

**Review by danielqiuu — DISMISSED** [review]
clean

**Comment by ethanrstark** [comment]
Fixed the merge conflicts :)

**Review by danielqiuu — DISMISSED** [review]

**Review by liu-samuel — DISMISSED** [review]
lgtm

**Review by helenastra — DISMISSED** [review]

**Review by helenastra — DISMISSED** [review]

**Comment by ethanrstark** [comment]
This pr is finally ready to be merged!! :D

**Review by danielqiuu — APPROVED** [review]

**Review by liu-samuel — APPROVED** [review]
nice, thank you for documenting

**Review by helenastra — APPROVED** [review]

**Pull request merged**
