### PR TITLE
updated gitignore

### PR DESCRIPTION
**Pull request by liu-samuel**

### CODE REVIEW

**Review by ericguo1230 — APPROVED** [review]

**Review by lukecheseldine — APPROVED** [review]

**Review by lukecheseldine — APPROVED** [review]

**Review by MarkianV — DISMISSED** [review]
Don't know what changed but Ill trust it.

**Review by helenastra — APPROVED** [review]

**Comment by liu-samuel** [comment]
github requires 3 reviews again after I change it so it passes checks :/ sorry

**Review by helenastra — APPROVED** [review]

**Review by danielqiuu — APPROVED** [review]
Good

**Review by lukecheseldine — APPROVED** [review]
thanks for fixing the tests!

**Pull request merged**
