### PR TITLE
Feature 4 register

### PR DESCRIPTION
**Pull request by ericguo1230**
Finished the Register Form GUI.

### CODE REVIEW

**Review by danielqiuu — DISMISSED** [review]

**Review by lukecheseldine — CHANGES_REQUESTED** [review]
looks really good eric! the only thing that didn't work was your validation. it's saying email already taken no matter what i put in. fix that and i think you're good to merge!
Screen Shot 2022-12-01 at 12 48 10 PM

**Comment by lukecheseldine** [comment]
ALSO, maybe the title can be like, "Create an account" or something like that, instead of Register Form lol

**Review by lukecheseldine — DISMISSED** [review]
great job!

**Review by lukecheseldine — DISMISSED** [review]
good job eric! this is a huge pr :)

**Review by danielqiuu — APPROVED** [review]
I just deleted the database files for you and fixed a merge conflict you had. But this looks like a good pr. Good job on writing tests for it as well. After this gets merged we should have a working app and all we have to do is start debugging and more testing.

**Review by claregillis — APPROVED** [review]
Looks great! Thanks for switching all GUIs from Form to Page!

**Review by ethanrstark — APPROVED** [review]

**Review by danielqiuu — APPROVED** [review]

**Review by claregillis — APPROVED** [review]
Resolved a couple conflicts - approved again

**Pull request merged**
