### PR TITLE
Show success or fail text and clear form on successful submission

### PR DESCRIPTION
**Pull request by danielqiuu**
As title states, I have made it so that there is text on successful listing creation and we clear the text box when that happens.
image

And when the details are bad, we show the following.
image

and if for whatever reason someone isnt logged in tries to create a listing, they see the following
image

### CODE REVIEW

**Review by lukecheseldine — APPROVED** [review]
great job daniel, looks snazzy!

**Review by helenastra — APPROVED** [review]
loooks goodd is it possible for someone to try to create a listing if they haven't logged in?

**Review by liu-samuel — APPROVED** [review]
lgtm

**Comment by danielqiuu** [comment]
> loooks goodd is it possible for someone to try to create a listing if they haven't logged in?

No, I dont think so. But better safe than sorry!

**Pull request merged**
