### PR TITLE
Changes to Register Page so that it works with Register Form

### PR DESCRIPTION
**Pull request by ericguo1230**
I just made some changes to the register page so that it calls MyForm (The GUI Class), let me know if you want me to change anything.

### CODE REVIEW

**Review by MarkianV — DISMISSED** [review]
Looks good.

**Review by liu-samuel — APPROVED** [review]
lgtm

**Review by helenastra — COMMENTED** [review]
Looks good but will there be any error message displays?

**Review by lukecheseldine — CHANGES_REQUESTED** [review]
eric, did you test this? i switched to your branch and i can't run the project because there are errors. if you aren't getting errors, lmk, but otherwise, please fix them and rerequest review. i would like to able to run it and see your page before approving 👍

**Pull request closed without merging**
