### PR TITLE
Add 2 buttons to NavBar

### PR DESCRIPTION
**Pull request by claregillis**
I added the Create Listing button, and the Logo as a button that takes you to the listings page in the NavBar. Reformatted very small things in Main and LoginPage.

Side note: fixed autograding!!

### CODE REVIEW

**Review by ethanrstark — COMMENTED** [review]
I think this is great, I like how you used a picture of our logo as a button to move between pages. When doing constraints in SpringLayout you can use the HORIZONTAL_CENTER or VERTICAL_CENTER attributes of SpringLayout to format it even nicer and more concisely rather than always hardcoding widths and height which is usually hard to tell when dealing with pixels. Very good work with the NavBar too, what would we do without you :,)

**Review by danielqiuu — APPROVED** [review]
thanks for adding the create listing button and I see that you have made it to change the current page to "Create Listing". Ill have to test it on my end to make sure all is good, but this can be added to main and Ill change it from there. Thanks!

**Review by lukecheseldine — APPROVED** [review]
it looks like you're touching a lot of the same files as in your other pr, so you might have to resolve conflicts to merge both. maybe not. anyways, looks great!

**Review by liu-samuel — APPROVED** [review]
lgtm

**Pull request merged**
